<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\JobsAggregator.Infrastructure\JobsAggregator.Infrastructure.csproj" />
    <ProjectReference Include="..\JobsAggregator.Domain\JobsAggregator.Domain.csproj" />
    <ProjectReference Include="..\JobsAggregator.Application\JobsAggregator.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.5" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
