<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\FriendshipCountdown.Infrastructure\FriendshipCountdown.Infrastructure.csproj" />
    <ProjectReference Include="..\FriendshipCountdown.Domain\FriendshipCountdown.Domain.csproj" />
    <ProjectReference Include="..\FriendshipCountdown.Application\FriendshipCountdown.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.5" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
